export const RETRIEVE_GROUP_SUCCESS = 'RETRIEVE_GROUP_SUCCESS';
export const RETRIEVE_ERROR = 'RETRIEVE_ERROR';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_ERROR = 'UPDATE_GROUP_ERROR';
