export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_ERROR = 'FETCH_PERSON_ERROR';

export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';

export const UPDATE_PERSON_ERROR = 'UPDATE_PERSON_ERROR';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
